controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
<<<<<<< HEAD
api_login_check:
    path: /login
=======
>>>>>>> c727633 (Add initial set of files)
